export const categoryOptions = [
  { value: "Electronics", label: "Electronics" },
  { value: "Furniture", label: "Furniture" },
  { value: "Clothing & Accessories", label: "Clothing & Accessories" },
  { value: "Books", label: "Books" },
  { value: "Home Appliances", label: "Home Appliances" },
  { value: "Toys & Games", label: "Toys & Games" },
  { value: "Sports & Outdoors", label: "Sports & Outdoors" },
  { value: "Vehicles", label: "Vehicles" },
  { value: "Real Estate", label: "Real Estate" },
  { value: "Musical Instruments", label: "Musical Instruments" },
  { value: "Collectibles", label: "Collectibles" },
  { value: "Tools & Equipment", label: "Tools & Equipment" },
  { value: "Health & Beauty", label: "Health & Beauty" },
  { value: "Pets & Pet Supplies", label: "Pets & Pet Supplies" },
  { value: "Bikes & Scooters", label: "Bikes & Scooters" },
];
export const cityOptions = [
  { value: "Dhaka", label: "Dhaka" },
  { value: "Chittagong", label: "Chittagong" },
  { value: "Khulna", label: "Khulna" },
  { value: "Rajshahi", label: "Rajshahi" },
  { value: "Sylhet", label: "Sylhet" },
  { value: "Barisal", label: "Barisal" },
  { value: "Rangpur", label: "Rangpur" },
  { value: "Mymensingh", label: "Mymensingh" },
  { value: "Narayanganj", label: "Narayanganj" },
  { value: "Comilla", label: "Comilla" },
  { value: "Bogra", label: "Bogra" },
  { value: "Rajbari", label: "Rajbari" },
  { value: "Pabna", label: "Pabna" },
  { value: "Jessore", label: "Jessore" },
  { value: "Cox's Bazar", label: "Cox's Bazar" },
  { value: "Tangail", label: "Tangail" },
  { value: "Gazipur", label: "Gazipur" },
  { value: "Narsingdi", label: "Narsingdi" },
  { value: "Faridpur", label: "Faridpur" },
  { value: "Manikganj", label: "Manikganj" },
];
export const conditionOptions = [
  { value: "new", label: "New" },
  { value: "used", label: "Used" },
];
